set(LIB_PYBIND11 "pybind11")
if(MSVC)
ExternalProject_Add(ADD_${LIB_PYBIND11}
        URL ${THIRDPARTY_URL}/pybind11-${PYBIND11_VERSION}.tar.gz
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CONFIGURE_COMMAND ${CMAKE_COMMAND} . -T${MSVC_TOOLSET_VERSION} -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/${LIB_PYBIND11}-${PYBIND11_VERSION} -DPYBIND11_TEST=OFF
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_PYBIND11}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${CMAKE_COMMAND} --build . --config release 
        URL_MD5 ${PYBIND11_MD5}
        )
else(MSVC)
ExternalProject_Add(ADD_${LIB_PYBIND11}
        URL ${THIRDPARTY_URL}/pybind11-${PYBIND11_VERSION}.tar.gz
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CONFIGURE_COMMAND ${CMAKE_COMMAND} . -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/${LIB_PYBIND11}-${PYBIND11_VERSION} -DPYBIND11_TEST=OFF
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_PYBIND11}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND make
        URL_MD5 ${PYBIND11_MD5}
        )
endif(MSVC)
        
add_dependencies(thirdparty ADD_${LIB_PYBIND11})

install(DIRECTORY ${THIRDPARTY_PATH}/${LIB_PYBIND11}-${PYBIND11_VERSION} USE_SOURCE_PERMISSIONS DESTINATION ${CMAKE_INSTALL_PREFIX})
INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}/${LIB_PYBIND11}-${PYBIND11_VERSION} ${CMAKE_INSTALL_PREFIX}/${LIB_PYBIND11})")
