set(LIB_SNAPPY "snappy")
if(MSVC)
ExternalProject_Add(ADD_${LIB_SNAPPY}
        URL ${THIRDPARTY_URL}/snappy-${SNAPPY_VERSION}.tar.gz
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CONFIGURE_COMMAND ${CMAKE_COMMAND} .  -T${MSVC_TOOLSET_VERSION}  -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/snappy-${SNAPPY_VERSION} -DSNAPPY_BUILD_TESTS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_SNAPPY}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND  ${CMAKE_COMMAND} --build . --config release --target ALL_BUILD -- /maxcpucount:4
        URL_MD5 ${SNAPPY_MD5}
        )

else(MSVC)
ExternalProject_Add(ADD_${LIB_SNAPPY}
        URL ${THIRDPARTY_URL}/snappy-${SNAPPY_VERSION}.tar.gz
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CONFIGURE_COMMAND ${CMAKE_COMMAND} . -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/snappy-${SNAPPY_VERSION} -DSNAPPY_BUILD_TESTS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_SNAPPY}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND make
        URL_MD5 ${SNAPPY_MD5}
        )

endif(MSVC)
        
add_dependencies(thirdparty ADD_${LIB_SNAPPY})

install(DIRECTORY ${THIRDPARTY_PATH}/snappy-${SNAPPY_VERSION} USE_SOURCE_PERMISSIONS DESTINATION ${CMAKE_INSTALL_PREFIX})

if(MSVC)
set(LINK_DST "${CMAKE_INSTALL_PREFIX}\\\\snappy")
set(LINK_SRC "${CMAKE_INSTALL_PREFIX}\\\\snappy-${SNAPPY_VERSION}")
INSTALL(CODE "EXECUTE_PROCESS(COMMAND cmd.exe /c mklink /J ${LINK_DST} ${LINK_SRC})")
file(APPEND ${LINK_FILE} "cmd /c mklink /J ${LINK_DST} ${LINK_SRC}\n")
# INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove_directory ${CMAKE_INSTALL_PREFIX}/snappy && ${CMAKE_COMMAND} -E copy_directory ${CMAKE_INSTALL_PREFIX}/snappy-${SNAPPY_VERSION} )")
else(MSVC)
INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}/snappy-${SNAPPY_VERSION} ${CMAKE_INSTALL_PREFIX}/snappy)")
endif(MSVC)

