
set(LIB_SQLITE3 "sqlite3")

if(MSVC)
    set(SQLITE3_CMAKE_ARGS ${SQLITE3_CMAKE_ARGS} -DCMAKE_USER_MAKE_RULES_OVERRIDE=${PROJECT_SOURCE_DIR}/cmake/compiler_flags_overrides.cmake )
endif()

if(MSVC)
ExternalProject_Add(ADD_${LIB_SQLITE3}
        URL ${THIRDPARTY_URL}/sqlite-amalgamation-${SQLITE3_VERSION}.zip
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CMAKE_ARGS ${SQLITE3_CMAKE_ARGS}
        PATCH_COMMAND  ${CMAKE_COMMAND} -E copy ${PROJECT_SOURCE_DIR}/contrib/sqlite3.txt ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib/CMakeLists.txt
        CONFIGURE_COMMAND ${CMAKE_COMMAND} ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib -DCMAKE_CXX_FLAGS=${MT_MODE_FLAG} -T${MSVC_TOOLSET_VERSION} -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/${LIB_SQLITE3}-${SQLITE3_VERSION} -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${CMAKE_COMMAND} --build . --config release -- /maxcpucount:4
        URL_MD5 ${SQLITE3_MD5}
    )

else(MSVC)
ExternalProject_Add(ADD_${LIB_SQLITE3}
        URL ${THIRDPARTY_URL}/sqlite-amalgamation-${SQLITE3_VERSION}.zip
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CMAKE_ARGS ${SQLITE3_CMAKE_ARGS}
        PATCH_COMMAND  ${CMAKE_COMMAND} -E copy ${PROJECT_SOURCE_DIR}/contrib/sqlite3.txt ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib/CMakeLists.txt
        CONFIGURE_COMMAND ${CMAKE_COMMAND} ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_PATH}/${LIB_SQLITE3}-${SQLITE3_VERSION} -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_SQLITE3}-lib
        BUILD_IN_SOURCE 0
        BUILD_COMMAND make
        URL_MD5 ${SQLITE3_MD5}
    )
endif(MSVC)
        
add_dependencies(thirdparty ADD_${LIB_SQLITE3})

install(DIRECTORY ${THIRDPARTY_PATH}/${LIB_SQLITE3}-${SQLITE3_VERSION} USE_SOURCE_PERMISSIONS DESTINATION ${CMAKE_INSTALL_PREFIX})

if(MSVC)
set(LINK_DST "${CMAKE_INSTALL_PREFIX}\\\\sqlite3")
set(LINK_SRC "${CMAKE_INSTALL_PREFIX}\\\\sqlite3-${SQLITE3_VERSION}")
INSTALL(CODE "EXECUTE_PROCESS(COMMAND cmd.exe /c mklink /J ${LINK_DST} ${LINK_SRC})")
file(APPEND ${LINK_FILE} "cmd /c mklink /J ${LINK_DST} ${LINK_SRC}\n")
# INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove_directory ${CMAKE_INSTALL_PREFIX}/sqlite3 && ${CMAKE_COMMAND} -E copy_directory ${CMAKE_INSTALL_PREFIX}/sqlite3-${SQLITE3_VERSION} )")
else(MSVC)
INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}/sqlite3-${SQLITE3_VERSION} ${CMAKE_INSTALL_PREFIX}/sqlite3)")
endif(MSVC)

