
set(LIB_UNIXODBC "unixodbc")

ExternalProject_Add(ADD_${LIB_UNIXODBC}
        URL ${THIRDPARTY_URL}/unixODBC-${UNIXODBC_VERSION}.tar.gz
        DOWNLOAD_DIR ${CMAKE_SOURCE_DIR}/download
        PREFIX ${CMAKE_BINARY_DIR}
        INSTALL_DIR ${CMAKE_SOURCE_DIR}
        CMAKE_ARGS ${SQLITE3_CMAKE_ARGS}
        CONFIGURE_COMMAND ./configure --enable-static --with-pic --prefix=${THIRDPARTY_PATH}/${LIB_UNIXODBC}-${UNIXODBC_VERSION}
        SOURCE_DIR ${THIRDPARTY_PATH}/${LIB_UNIXODBC}-lib
        BUILD_IN_SOURCE 1
        BUILD_COMMAND make
        URL_MD5 ${UNIXODBC_MD5}
        )

add_dependencies(thirdparty ADD_${LIB_UNIXODBC})

install(DIRECTORY ${THIRDPARTY_PATH}/${LIB_UNIXODBC}-${UNIXODBC_VERSION} USE_SOURCE_PERMISSIONS DESTINATION ${CMAKE_INSTALL_PREFIX})
INSTALL(CODE "EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}/${LIB_UNIXODBC}-${UNIXODBC_VERSION} ${CMAKE_INSTALL_PREFIX}/${LIB_UNIXODBC})")
