name: C/C++ linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: make build; cd build;cmake .. -DCMAKE_INSTALL_PREFIX=dist
      - name: make
        run: cd build; make
      - name: Compress build output
        run: |
          tar czf dist-linux.tgz build/
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist-linux.tgz