name: C/C++ linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: cd build;cmake ..
      - name: make
        run: cd build; make
