name: C/C++ mac

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
          brew update
          brew upgrade gettext autoconf libtool 
          brew install automake
          brew install texinfo
          makeinfo --version
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          # 缓存的键，用于区分不同的缓存项
          path: ./download
          key: download-cache-mac
      - name: configure
        run: mkdir build; cd build;cmake .. -DCMAKE_INSTALL_PREFIX=dist
      - name: make
        run: cd build; make
      - name: Compress build output
        run: |
          tar czf dist-mac.tgz build/
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist-mac.tgz