name: C/C++ mac

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
          brew update
          brew install gettext autoconf libtool automake@1.15
      - uses: actions/checkout@v3
      - name: configure
        run: mkdir build; cd build;cmake .. -DCMAKE_INSTALL_PREFIX=dist
      - name: make
        run: cd build; make
      - name: Compress build output
        run: |
          tar czf dist-mac.tgz build/
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist-mac.tgz