name: C/C++ win tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.18"
          distribution: strawberry
      - run: perl -V
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          # 缓存的键，用于区分不同的缓存项
          path: download
          key: ${{ runner.os }}-download
      - name: configure
        run: mkdir build; cd build; cmake --version; cmake .. -DCMAKE_INSTALL_PREFIX=dist -DBUILD_SHARED_LIBS=ON
      - name: make
        run: cd build; cmake --build . --config release --target ALL_BUILD; cmake --build . --config release --target install
      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
      - name: Compress build output
        run: |
          cd build; cmake -E tar czf dist-${{ runner.os }}-${{ steps.get_version.outputs.VERSION }}.tgz dist/; cmake -E copy dist-${{ runner.os }}-${{ steps.get_version.outputs.VERSION }}.tgz ../
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist-${{ runner.os }}-${{ steps.get_version.outputs.VERSION }}.tgz"
          allowUpdates: true
          token: ${{ secrets.RELEASE_TOKEN }}
          name: "${{ steps.get_version.outputs.VERSION }}"
  save_cache_job:
    needs: build  # Ensure this job runs after the first job
    runs-on: windows-2019

    steps:
      # Post step to save the cache regardless of job status
      - name: Save cache regardless of job status
        if: always()  # This ensures the step is executed regardless of job status
        run: |
          # This step is empty as it doesn't need to do anything
          # The existence of this step with `if: always()` ensures the cache will be saved even if the job fails