name: C/C++ win

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"
          distribution: strawberry
      - run: perl -V
      - uses: actions/checkout@v3
      - name: configure
        run: mkdir build; cd build; cmake --version; cmake ..
      - name: make
        run: cd build; cmake --build . --config release
